services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: textile_app
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: textile_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - app

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: textile_bot
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
    command: python -m bot_app.main
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: textile_db
    environment:
      POSTGRES_DB: textile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1"
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d textile"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
